# Generated by Django 5.1.5 on 2026-08-20 08:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text="Defaults to the unit's rent when omitted on create.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Computed: whole months plus a pro-rated remainder. Never client-set.', max_digits=14)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='members.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.unit')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['unit', 'start_date', 'end_date'], name='contract_unit_range_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('monthly_rent__gt', 0)), name='contract_monthly_rent_positive')],
            },
        ),
    ]
