# Generated by Django 5.1.5 on 2026-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(help_text='Unique across members; used to identify a returning tenant.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
    ]
